# Generated by Django 3.1.7 on 2021-03-27 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_head', models.CharField(max_length=200)),
                ('story_description', models.TextField(max_length=1000)),
                ('story_type', models.CharField(choices=[('BIRTHDAY', 'BIRTHDAY'), ('WEDDING', 'WEDDING'), ('RE-UNION', 'RE-UNION'), ('HANG OUT', 'HANG OUT'), ('TRAVEL', 'TRAVEL'), ('OTHER', 'OTHER')], default='OTHER', max_length=20)),
                ('story_date', models.DateField(blank=True, null=True)),
                ('story_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserStoryRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='story.story')),
            ],
        ),
        migrations.CreateModel(
            name='Moments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moment_head', models.CharField(max_length=200)),
                ('moment_description', models.CharField(max_length=1000)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='story.story')),
            ],
        ),
    ]
